spring:
  datasource:
    url: jdbc:postgresql://db:5432/prod_db
    username: postgres
    password: postgres

  jpa:
    open-in-view: false
    properties:
      hibernate:
        search:
          backend:
            type: elasticsearch
            hosts: elasticsearch:9200

