spring:
  profiles:
    default: dev

#    active: prod

  application:
    name: micro-search
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  elasticsearch:
    restclient:
      sniffer:
        interval: 60m
        delay-after-failure: 30m

server:
  port: 8083

micro-search:
  openapi:
    dev-url: http://localhost:8083
    prod-url: micro-search:8083

springdoc:
  swagger-ui:
    url: /swagger.yaml




