spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news_comments
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        search:
          backend:
            type: elasticsearch
            hosts: localhost:9200



