openapi: 3.0.0
info:
  title: Search-part API
  version: 1.0.0
paths:
  /search/news:
    get:
      summary: Search news
      parameters:
        - name: text
          in: query
          required: true
          schema:
            type: string
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          description: Number of items per page for pagination
          required: false
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: A list of news
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/NewsResponseDto'
  /search/comments:
    get:
      summary: Search comments
      parameters:
        - name: text
          in: query
          required: true
          schema:
            type: string
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          description: Number of items per page for pagination
          required: false
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: A list of comments
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/CommentResponseDto'
components:
  schemas:
    NewsResponseDto:
      type: object
      properties:
        id:
          type: integer
          example: 1
        time:
          type: string
          format: date-time
          example: "2024-03-04T20:15:41.3008788"
        updateTime:
          type: string
          format: date-time
          example: "2024-03-04T20:15:41.3008788"
        title:
          type: string
          example: "Example News Title"
        text:
          type: string
          example: "Example News Text"
    CommentResponseDto:
      type: object
      properties:
        id:
          type: integer
          example: 1
        time:
          type: string
          format: date-time
          example: "2024-03-04T20:15:41.3008788"
        updateTime:
          type: string
          format: date-time
          example: "2024-03-04T20:15:41.3008788"
        text:
          type: string
          example: "Example Comment Text"
        username:
          type: string
          example: "Example Username"
        newsId:
          type: integer
          example: 1